#pragma once

#include "common_def.h"

#define N_OTE_PEN				8
#define N_OTE_BRUSH				8

#define OTE0_WHITE              0
#define OTE0_GLAY               1
#define OTE0_RED                2
#define OTE0_BLUE               3
#define OTE0_GREEN              4
#define OTE0_YELLOW             5
#define OTE0_MAZENDA            6 
#define OTE0_ORANGE				7


//オブジェクトID
#define BASE_ID_OTE_STATIC			10700
//STATIC ID 0-31は、PBランプ用予約領域
#define ID_OTE_LAMP_HIJYOU		0	//非常停止PB
#define ID_OTE_LAMP_SYUKAN		1	//主幹PB
#define ID_OTE_LAMP_KIDOU		2
#define ID_OTE_LAMP_TEISHI		3
#define ID_OTE_LAMP_AUTO		4
#define ID_OTE_LAMP_FUREDOME	5
#define ID_OTE_LAMP_S1			6
#define ID_OTE_LAMP_S2			7
#define ID_OTE_LAMP_S3			8
#define ID_OTE_LAMP_N1			9
#define ID_OTE_LAMP_N2			10
#define ID_OTE_LAMP_N3			11
#define ID_OTE_LAMP_WIDE		12
#define ID_OTE_LAMP_ZOOM		13
#define ID_OTE_LAMP_HOOK		14
#define ID_OTE_LAMP_OPE			15
#define ID_OTE_LAMP_COM			16
#define ID_OTE_LAMP_MODE		17
#define ID_OTE_LAMP_FAULT		18
#define ID_OTE_LAMP_MOMENT		19

#define ID_OTE_LABEL_MH				32
#define ID_OTE_LABEL_AH				33
#define ID_OTE_LABEL_BH				34
#define ID_OTE_LABEL_SL				35
#define ID_OTE_LABEL_GT				36
#define ID_OTE_INF_MH0				37
#define ID_OTE_INF_AH0				38
#define ID_OTE_INF_BH0				39
#define ID_OTE_INF_SL0				40
#define ID_OTE_INF_GT0				41
#define ID_OTE_INF_SWAY_MH			42
#define ID_OTE_INF_SWAY_AH			43
#define ID_OTE_SUB_CONNECT_HEAD		44
#define ID_OTE_SUB_CONNECT_BODY		45

#define BASE_ID_OTE_PB		10800
#define ID_OTE_PB_HIJYOU		0	//非常停止PB
#define ID_OTE_PB_SYUKAN		1	//主幹PB
#define ID_OTE_PB_KIDOU			2
#define ID_OTE_PB_TEISHI		3
#define ID_OTE_PB_AUTO			4
#define ID_OTE_PB_FUREDOME		5
#define ID_OTE_PB_S1			6
#define ID_OTE_PB_S2			7
#define ID_OTE_PB_S3			8
#define ID_OTE_PB_N1			9
#define ID_OTE_PB_N2			10
#define ID_OTE_PB_N3			11
#define ID_OTE_CHK_WIDE			12
#define ID_OTE_CHK_ZOOM			13
#define ID_OTE_CHK_HOOK			14
#define ID_OTE_CHK_OPE			15
#define ID_OTE_RADIO_COM		16
#define ID_OTE_RADIO_MODE		17
#define ID_OTE_RADIO_FAULT		18
#define ID_OTE_RADIO_MOMENT		19
#define ID_OTE_RADIO_SOU		20
#define ID_OTE_RADIO_RPU		21
#define ID_OTE_RADIO_SOM		22
#define ID_OTE_RADIO_ROM		23
#define ID_OTE_RADIO_RPM		24

//ノッチID　BASE + 10*MOTION_ID + NOTCH
#define BASE_ID_OTE_NOTCH		11010
#define ID_OTE_NOTCH_MH0		11010
#define ID_OTE_NOTCH_AH0		11510		//表示更新停止
#define ID_OTE_NOTCH_BH0		11310
#define ID_OTE_NOTCH_GT0		11110
#define ID_OTE_NOTCH_SL0		11410

#define N_OTE_NOTCH_ARRAY		10			//ノッチ割り当て配列数
#define N_OTE_NOTCH_MAX			4			

#define N_OTE_CTRL_TYPE			3
#define ID_OTE_CTRL_STATIC		0
#define ID_OTE_CTRL_PB			1
#define ID_OTE_CTRL_NOTCH		2

#define N_OTE_PNL_ITEMS			64
#define N_OTE_PNL_STATIC		64
#define N_OTE_PNL_NOTCH			64
#define N_OTE_PNL_PB			64

#define N_OTE_HBMAP				8
#define ID_OTE_HBMAP_MEM0		0
#define ID_OTE_HBMAP_MEM_IF		1

#define N_OTE_HDC				8
#define ID_OTE_HDC_MEM0			0
#define ID_OTE_HDC_MEM_IF		1

#define ID_OTE_LAMP_WHITE		0
#define ID_OTE_LAMP_GLAY		1
#define ID_OTE_LAMP_RED			2
#define ID_OTE_LAMP_GREEN		3

#define PRM_OTE_DEF_PB_W		50
#define PRM_OTE_DEF_PB_W2		30
#define PRM_OTE_DEF_PB_H		20
#define PRM_OTE_DEF_LAMP_W		5
#define PRM_OTE_DEF_LAMP_H		20

#define PRM_LAMP_CHK_CNT		20
#define PRM_LAMP_FLICK_CNT		10	//ランプON判定カウント　counter%PRM_LAMP_CHK_CNTがこの値より大でOFF

#define PRM_POINT_X_LABEL_BH	20
#define PRM_POINT_X_LABEL_MH	760
#define PRM_POINT_Y_LABEL_SL	250
#define PRM_POINT_Y_LABEL_BH	290
#define PRM_POINT_Y_LABEL_GT	530
#define PRM_POINT_Y_NOTCH_SL	250

#define OTE0_PB_SET_COUNT		100
#define OTE0_LAMP_FLICK_COUNT	50

//操作端末ウィンドウ構造体
typedef struct _stOTEWorkWnd {
	int area_x = 0, area_y = 0, area_w = 0, area_h = 0;     //メインウィンドウ上の表示エリア(デバイスコンテキスト用）
	int bmp_w, bmp_h;             //グラフィックビットマップサイズ
	int lamp_status[N_OTE_PNL_PB];						//ランプ状態
	int connect_wnd_item = ID_OTE_RADIO_SOU;

	HIMAGELIST hImgLamp0;									//釦ランプのイメージリストハンドル

	HBITMAP hBmap[N_OTE_HBMAP];								//ビットマップハンドル
	HDC		hdc[N_OTE_HDC];			//メモリデバイスコンテキスト
	HPEN	hpen[N_OTE_PEN] = { NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL };
	HBRUSH	hbrush[N_OTE_BRUSH] = { NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL };
	HWND	hctrl[N_OTE_CTRL_TYPE][N_OTE_PNL_STATIC];
	HFONT	hfont_inftext = NULL;				                //テキスト用フォント
	BLENDFUNCTION bf = { 0,0,0,0 };					        //半透過設定構造体

	UINT32 pb_stat[N_OTE_PNL_PB];
	INT32  notch_pos[MOTION_ID_MAX] = { 0,0,0,0,0,0,0,0 };

	POINT pt_ctrl[N_OTE_CTRL_TYPE][N_OTE_PNL_ITEMS] = {
		//#STATIC
		//LAMP
		  //メインパネル
		  770,5,710,5,650,5,590,5,
		  590,30,650,30,710,30,770,30,
		  590,55,650,55,710,55,770,55,
		  590,80,650,80,710,80,770,80,
		  590,105,650,105,710,105,770,105,
		  //CONNECTパネル　ID_OTE_RADIO_SOU	ID_OTE_RADIO_RPU ID_OTE_RADIO_SOM ID_OTE_RADIO_ROM ID_OTE_RADIO_RPM
		  5,5,55,5,105,5,155,5,205,5,
		  0,0,0,0,0,0,0,0,0,0,0,0,0,0,				//16
		//LABEL
		//ID_OTE_LABEL_MH	         ID_OTE_LABEL_AH	         ID_OTE_LABEL_BH	     ID_OTE_LABEL_SL            ID_OTE_LABEL_GT
		  780,PRM_POINT_Y_LABEL_BH,  720,PRM_POINT_Y_LABEL_BH , 20,PRM_POINT_Y_LABEL_BH,  90,PRM_POINT_Y_LABEL_SL,  90,PRM_POINT_Y_LABEL_GT,
		 //INF
		 //ID_OTE_INF_MH0  ID_OTE_INF_AH0 ID_OTE_INF_BH0	 ID_OTE_INF_SL0	 ID_OTE_INF_GT0	 ID_OTE_INF_SWAY_MH	 ID_OTE_INF_SWAY_AH	
		  400,300,         600,300,       100,300,          250,300,      500,475,            400,20,                550,20,
		 //ID_OTE_SUB_CONNECT_HEAD   ID_OTE_SUB_CONNECT_BODY	
		  5,30,                        5,85,
		  0,0,0,0,												//16
		  0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,//16

		  //#PB
		  //メインパネル
		  770,5,710,5,650,5,590,5,
		  590,30,650,30,710,30,770,30,
		  590,55,650,55,710,55,770,55,
		  590,80,650,80,710,80,770,80,
		  590,105,650,105,710,105,770,105,
		  //CONNECTパネル　ID_OTE_RADIO_SOU	ID_OTE_RADIO_RPU ID_OTE_RADIO_SOM ID_OTE_RADIO_ROM ID_OTE_RADIO_RPM
		  5,5,55,5,105,5,155,5,205,5,
		  0,0,0,0,0,0,0,0,0,0,0,0,0,0,				//16
		  0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,//16
		  0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,//16

		  //#NOTCH
		  800,520,800,495,800,470,800,445,800,420,800,395,800,370,800,345,800,320,0,0,//HOIST
		  150,PRM_POINT_Y_LABEL_GT,205,PRM_POINT_Y_LABEL_GT,260,PRM_POINT_Y_LABEL_GT,315,PRM_POINT_Y_LABEL_GT,370,PRM_POINT_Y_LABEL_GT,425,PRM_POINT_Y_LABEL_GT,480,PRM_POINT_Y_LABEL_GT,535,PRM_POINT_Y_LABEL_GT,590,PRM_POINT_Y_LABEL_GT,0,0,//GT
		  0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,//-
		  40,520,40,495,40,470,40,445,40,420,40,395,40,370,40,345,40,320,0,0,//BH
		  150,PRM_POINT_Y_NOTCH_SL,205,PRM_POINT_Y_NOTCH_SL,260,PRM_POINT_Y_NOTCH_SL,315,PRM_POINT_Y_NOTCH_SL,370,PRM_POINT_Y_NOTCH_SL,425,PRM_POINT_Y_NOTCH_SL,480,PRM_POINT_Y_NOTCH_SL,535,PRM_POINT_Y_NOTCH_SL,590,PRM_POINT_Y_NOTCH_SL,0,0,//SL
		  740,520,740,495,740,470,740,445,740,420,740,395,740,370,740,345,740,320,0,0,//AH
		  0,0,0,0,0,0,0,0
	};

	SIZE size_ctrl[N_OTE_CTRL_TYPE][N_OTE_PNL_STATIC] = {
		//#STATIC
		//LAMP
		   //メインパネル
		   PRM_OTE_DEF_LAMP_W,PRM_OTE_DEF_LAMP_H,PRM_OTE_DEF_LAMP_W,PRM_OTE_DEF_LAMP_H,PRM_OTE_DEF_LAMP_W,PRM_OTE_DEF_LAMP_H,PRM_OTE_DEF_LAMP_W,PRM_OTE_DEF_LAMP_H,
		   PRM_OTE_DEF_LAMP_W,PRM_OTE_DEF_LAMP_H,PRM_OTE_DEF_LAMP_W,PRM_OTE_DEF_LAMP_H,PRM_OTE_DEF_LAMP_W,PRM_OTE_DEF_LAMP_H,PRM_OTE_DEF_LAMP_W,PRM_OTE_DEF_LAMP_H,
		   PRM_OTE_DEF_LAMP_W,PRM_OTE_DEF_LAMP_H,PRM_OTE_DEF_LAMP_W,PRM_OTE_DEF_LAMP_H,PRM_OTE_DEF_LAMP_W,PRM_OTE_DEF_LAMP_H,PRM_OTE_DEF_LAMP_W,PRM_OTE_DEF_LAMP_H,
		   PRM_OTE_DEF_LAMP_W,PRM_OTE_DEF_LAMP_H,PRM_OTE_DEF_LAMP_W,PRM_OTE_DEF_LAMP_H,PRM_OTE_DEF_LAMP_W,PRM_OTE_DEF_LAMP_H,PRM_OTE_DEF_LAMP_W,PRM_OTE_DEF_LAMP_H,
		   PRM_OTE_DEF_LAMP_W,PRM_OTE_DEF_LAMP_H,PRM_OTE_DEF_LAMP_W,PRM_OTE_DEF_LAMP_H,PRM_OTE_DEF_LAMP_W,PRM_OTE_DEF_LAMP_H,PRM_OTE_DEF_LAMP_W,PRM_OTE_DEF_LAMP_H,
		   //CONNECTパネル　ID_OTE_RADIO_SOU ID_OTE_RADIO_RPU                  ID_OTE_RADIO_SOM                ID_OTE_RADIO_ROM                        ID_OTE_RADIO_RPM
		   PRM_OTE_DEF_LAMP_W,PRM_OTE_DEF_LAMP_H,PRM_OTE_DEF_LAMP_W,PRM_OTE_DEF_LAMP_H,PRM_OTE_DEF_LAMP_W,PRM_OTE_DEF_LAMP_H,PRM_OTE_DEF_LAMP_W,PRM_OTE_DEF_LAMP_H,PRM_OTE_DEF_LAMP_W,PRM_OTE_DEF_LAMP_H,
		   0,0,0,0,0,0,0,0,0,0,0,0,0,0,				//16
		//LABEL
		//ID_OTE_LABEL_MH	ID_OTE_LABEL_AH	  ID_OTE_LABEL_BH	ID_OTE_LABEL_SL   ID_OTE_LABEL_GT
		  50,20,            50,20,            50,20,            50,20,             50,20,
		  //INF
		  //ID_OTE_INF_MH0  ID_OTE_INF_AH0 ID_OTE_INF_BH0 ID_OTE_INF_SL0	 ID_OTE_INF_GT0	 ID_OTE_INF_SWAY_MH	 ID_OTE_INF_SWAY_AH	
			 100,150,         100,150,       100,150,       100,150,        150,50,            100,150,         100,150,
		  //ID_OTE_SUB_CONNECT_HEAD   ID_OTE_SUB_CONNECT_BODY
		   280,50,280,200,
		   0,0,0,0,												//16
		   0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,//16


		   //#PB
		   //メインパネル
		   PRM_OTE_DEF_PB_W,PRM_OTE_DEF_PB_H,PRM_OTE_DEF_PB_W,PRM_OTE_DEF_PB_H,PRM_OTE_DEF_PB_W,PRM_OTE_DEF_PB_H,PRM_OTE_DEF_PB_W,PRM_OTE_DEF_PB_H,
		   PRM_OTE_DEF_PB_W,PRM_OTE_DEF_PB_H,PRM_OTE_DEF_PB_W,PRM_OTE_DEF_PB_H,PRM_OTE_DEF_PB_W,PRM_OTE_DEF_PB_H,PRM_OTE_DEF_PB_W,PRM_OTE_DEF_PB_H,
		   PRM_OTE_DEF_PB_W,PRM_OTE_DEF_PB_H,PRM_OTE_DEF_PB_W,PRM_OTE_DEF_PB_H,PRM_OTE_DEF_PB_W,PRM_OTE_DEF_PB_H,PRM_OTE_DEF_PB_W,PRM_OTE_DEF_PB_H,
		   PRM_OTE_DEF_PB_W,PRM_OTE_DEF_PB_H,PRM_OTE_DEF_PB_W,PRM_OTE_DEF_PB_H,PRM_OTE_DEF_PB_W,PRM_OTE_DEF_PB_H,PRM_OTE_DEF_PB_W,PRM_OTE_DEF_PB_H,
		   PRM_OTE_DEF_PB_W,PRM_OTE_DEF_PB_H,PRM_OTE_DEF_PB_W,PRM_OTE_DEF_PB_H,PRM_OTE_DEF_PB_W,PRM_OTE_DEF_PB_H,PRM_OTE_DEF_PB_W,PRM_OTE_DEF_PB_H,
		   //CONNECTパネル　ID_OTE_RADIO_SOU ID_OTE_RADIO_RPU                  ID_OTE_RADIO_SOM                ID_OTE_RADIO_ROM                        ID_OTE_RADIO_RPM
		   PRM_OTE_DEF_PB_W,PRM_OTE_DEF_PB_H,PRM_OTE_DEF_PB_W,PRM_OTE_DEF_PB_H,PRM_OTE_DEF_PB_W,PRM_OTE_DEF_PB_H,PRM_OTE_DEF_PB_W,PRM_OTE_DEF_PB_H,PRM_OTE_DEF_PB_W,PRM_OTE_DEF_PB_H,
		   0,0,0,0,0,0,0,0,0,0,0,0,0,0,				//16
		   0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,//16
		   0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,//16

		   //#NOTCH
		   PRM_OTE_DEF_PB_W2,PRM_OTE_DEF_PB_H,PRM_OTE_DEF_PB_W2,PRM_OTE_DEF_PB_H,PRM_OTE_DEF_PB_W2,PRM_OTE_DEF_PB_H,PRM_OTE_DEF_PB_W2,PRM_OTE_DEF_PB_H,PRM_OTE_DEF_PB_W2,PRM_OTE_DEF_PB_H,PRM_OTE_DEF_PB_W2,PRM_OTE_DEF_PB_H,PRM_OTE_DEF_PB_W2,PRM_OTE_DEF_PB_H,PRM_OTE_DEF_PB_W2,PRM_OTE_DEF_PB_H,PRM_OTE_DEF_PB_W2,PRM_OTE_DEF_PB_H,0,0,//HOIST
		   PRM_OTE_DEF_PB_W2,PRM_OTE_DEF_PB_H,PRM_OTE_DEF_PB_W2,PRM_OTE_DEF_PB_H,PRM_OTE_DEF_PB_W2,PRM_OTE_DEF_PB_H,PRM_OTE_DEF_PB_W2,PRM_OTE_DEF_PB_H,PRM_OTE_DEF_PB_W2,PRM_OTE_DEF_PB_H,PRM_OTE_DEF_PB_W2,PRM_OTE_DEF_PB_H,PRM_OTE_DEF_PB_W2,PRM_OTE_DEF_PB_H,PRM_OTE_DEF_PB_W2,PRM_OTE_DEF_PB_H,PRM_OTE_DEF_PB_W2,PRM_OTE_DEF_PB_H,0,0,//GT
		   PRM_OTE_DEF_PB_W2,PRM_OTE_DEF_PB_H,PRM_OTE_DEF_PB_W2,PRM_OTE_DEF_PB_H,PRM_OTE_DEF_PB_W2,PRM_OTE_DEF_PB_H,PRM_OTE_DEF_PB_W2,PRM_OTE_DEF_PB_H,PRM_OTE_DEF_PB_W2,PRM_OTE_DEF_PB_H,PRM_OTE_DEF_PB_W2,PRM_OTE_DEF_PB_H,PRM_OTE_DEF_PB_W2,PRM_OTE_DEF_PB_H,PRM_OTE_DEF_PB_W2,PRM_OTE_DEF_PB_H,PRM_OTE_DEF_PB_W2,PRM_OTE_DEF_PB_H,0,0,//-
		   PRM_OTE_DEF_PB_W2,PRM_OTE_DEF_PB_H,PRM_OTE_DEF_PB_W2,PRM_OTE_DEF_PB_H,PRM_OTE_DEF_PB_W2,PRM_OTE_DEF_PB_H,PRM_OTE_DEF_PB_W2,PRM_OTE_DEF_PB_H,PRM_OTE_DEF_PB_W2,PRM_OTE_DEF_PB_H,PRM_OTE_DEF_PB_W2,PRM_OTE_DEF_PB_H,PRM_OTE_DEF_PB_W2,PRM_OTE_DEF_PB_H,PRM_OTE_DEF_PB_W2,PRM_OTE_DEF_PB_H,PRM_OTE_DEF_PB_W2,PRM_OTE_DEF_PB_H,0,0,//BH
		   PRM_OTE_DEF_PB_W2,PRM_OTE_DEF_PB_H,PRM_OTE_DEF_PB_W2,PRM_OTE_DEF_PB_H,PRM_OTE_DEF_PB_W2,PRM_OTE_DEF_PB_H,PRM_OTE_DEF_PB_W2,PRM_OTE_DEF_PB_H,PRM_OTE_DEF_PB_W2,PRM_OTE_DEF_PB_H,PRM_OTE_DEF_PB_W2,PRM_OTE_DEF_PB_H,PRM_OTE_DEF_PB_W2,PRM_OTE_DEF_PB_H,PRM_OTE_DEF_PB_W2,PRM_OTE_DEF_PB_H,PRM_OTE_DEF_PB_W2,PRM_OTE_DEF_PB_H,0,0,//SL
		   PRM_OTE_DEF_PB_W2,PRM_OTE_DEF_PB_H,PRM_OTE_DEF_PB_W2,PRM_OTE_DEF_PB_H,PRM_OTE_DEF_PB_W2,PRM_OTE_DEF_PB_H,PRM_OTE_DEF_PB_W2,PRM_OTE_DEF_PB_H,PRM_OTE_DEF_PB_W2,PRM_OTE_DEF_PB_H,PRM_OTE_DEF_PB_W2,PRM_OTE_DEF_PB_H,PRM_OTE_DEF_PB_W2,PRM_OTE_DEF_PB_H,PRM_OTE_DEF_PB_W2,PRM_OTE_DEF_PB_H,PRM_OTE_DEF_PB_W2,PRM_OTE_DEF_PB_H,0,0,//AH
		   0,0,0,0,0,0,0,0
	};

	WCHAR ctrl_text[N_OTE_CTRL_TYPE][N_OTE_PNL_STATIC][128] = {
		//STATIC
		L"",L"",L"",L"",L"",L"",L"",L"",L"",L"",L"",L"",L"",L"",L"",L"",
		L"",L"",L"",L"",L"",L"",L"",L"",L"",L"",L"",L"",L"",L"",L"",L"",
		L"MH",L"AH",L"BH",L"SL",L"GT",L"INF MH",L"INF AH",L"INF BH",L"INF SL",L"INF GT",L"",L"",L"HEAD -",L"BODY -",L"",L"",
		L"",L"",L"",L"",L"",L"",L"",L"",L"",L"",L"",L"",L"",L"",L"",L"",


		//PB
		L"非常",L"主幹",L"起動",L"停止",L"自動",L"振止",L"S1",L"S2",L"S3",L"N1",L"N2",L"N3",L"WIDE",L"ZOOM",L"HOOK",L"OPE",
		L"通信",L"MODE",L"故障",L"MOM",L"SOU",L"RPU",L"SOM",L"ROM",L"RPM",L"",L"",L"",L"",L"",L"",L"",
		L"",L"",L"",L"",L"",L"",L"",L"",L"",L"",L"",L"",L"",L"",L"",L"",
		L"",L"",L"",L"",L"",L"",L"",L"",L"",L"",L"",L"",L"",L"",L"",L"",

		//NOTCH
		L"-4",L"-3",L"-2",L"-1",L"0",L"1",L"2",L"3",L"4",L"",//MH
		L"-4",L"-3",L"-2",L"-1",L"0",L"1",L"2",L"3",L"4",L"",//GT
		L"-4",L"-3",L"-2",L"-1",L"0",L"1",L"2",L"3",L"4",L"",
		L"-4",L"-3",L"-2",L"-1",L"0",L"1",L"2",L"3",L"4",L"",//BH
		L"-4",L"-3",L"-2",L"-1",L"0",L"1",L"2",L"3",L"4",L"",//SL
		L"-4",L"-3",L"-2",L"-1",L"0",L"1",L"2",L"3",L"4",L"",//AH
		L"",L"",L"",L""
	};

}ST_OTE_WORK_WND, * LPST_OTE_WORK_WND;



